name: Release

on:
  workflow_call:
    inputs:
      openhab:
        description: 'Turns "openHAB" mode for build which assume certain branch policies (3.*=java 11, 4.*=java 17)'
        required: false
        default: false
        type: boolean
      release_version:
        description: 'The version to be released from actual HEAD revision'
        required: false
        default: 'X.Y.Z'
        type: string
      development_version:
        description: 'Version to be set as next, after release is made (appends commit to HEAD revision)'
        required: false
        default: 'X.Y.Z-SNAPSHOT'
        type: string
      perform_version:
        description: 'Tag which should be used to perform release and publish its artifacts'
        default: 'X.Y.Z'
        required: false
        type: string
      dry_run:
        # github have troubles handing this as a boolean
        description: 'Should execution abstain from mutating repository/remote state?'
        required: true
        default: 'true'
        type: string

      server_id:
        description: 'Server id used in case if results are deployed'
        required: false
        default: 'sonatype-nexus-staging'
        type: string
      java_version:
        description: 'Java version used for build, used only when openhab input is not true'
        required: false
        default: 11
        type: number
      additional_profiles:
        description: 'Profiles which should be activated during the build'
        required: false
        default: ''
        type: string
    secrets:
      GPG_PASSPHRASE:
        required: true
        description: 'GPG key passphrase used to access private key'
      GPG_PRIVATE_KEY:
        required: true
        description: 'GPG key used to sign release artifacts'
      CI_RELEASE_USERNAME:
        required: true
        description: 'Username used for deployment'
      CI_RELEASE_PASSWORD:
        required: true
        description: 'Password used for deployment'

jobs:
  release:
    if: ${{ !inputs.openhab }}
    permissions:
      contents: write
    uses: './.github/workflows/maven-release.yml'
    secrets:
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      CI_RELEASE_USERNAME: ${{ secrets.CI_RELEASE_USERNAME }}
      CI_RELEASE_PASSWORD: ${{ secrets.CI_RELEASE_PASSWORD }}
    with:
      release_version: ${{ inputs.release_version }}
      development_version: ${{ inputs.development_version }}
      perform_version: ${{ inputs.perform_version }}
      dry_run: ${{ inputs.dry_run == true || inputs.dry_run == 'true' }}
      server_id: ${{ inputs.server_id }}
      java_version: ${{ inputs.java_version }}
      additional_profiles: ${{ inputs.additional_profiles }}

  release_oh3:
    # github.ref is set with workflow dispatch event
    if: ${{ inputs.openhab && startsWith(github.ref_name, '3.') }}
    permissions:
      contents: write
    uses: './.github/workflows/maven-release.yml'
    secrets:
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      CI_RELEASE_USERNAME: ${{ secrets.CI_RELEASE_USERNAME }}
      CI_RELEASE_PASSWORD: ${{ secrets.CI_RELEASE_PASSWORD }}
    with:
      release_version: ${{ inputs.release_version }}
      development_version: ${{ inputs.development_version }}
      perform_version: ${{ inputs.perform_version }}
      dry_run: ${{ inputs.dry_run == true || inputs.dry_run == 'true' }}
      server_id: ${{ inputs.server_id }}
      java_version: 11
      additional_profiles: ${{ inputs.additional_profiles }}

  release_oh4:
    if: ${{ inputs.openhab && startsWith(github.ref_name, '4.') }}
    permissions:
      contents: write
    uses: './.github/workflows/maven-release.yml'
    secrets:
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      CI_RELEASE_USERNAME: ${{ secrets.CI_RELEASE_USERNAME }}
      CI_RELEASE_PASSWORD: ${{ secrets.CI_RELEASE_PASSWORD }}
    with:
      release_version: ${{ inputs.release_version }}
      development_version: ${{ inputs.development_version }}
      perform_version: ${{ inputs.perform_version }}
      dry_run: ${{ inputs.dry_run == true || inputs.dry_run == 'true' }}
      server_id: ${{ inputs.server_id }}
      java_version: 17
      additional_profiles: ${{ inputs.additional_profiles }}
